### ISSUE TITLE
markdown五级标题没有行高，会重叠

### ISSUE THREAD

**Issue by SunSeekerX** [Tokinx/Adams#27]
markdown五级标题没有行高，会重叠

```css
/* Connent */
.post_article img {max-width:100%;display:block;margin:auto;height:auto;}
.post_article embed {max-width:100%;margin:10px auto;display:block;}
.post_article a {text-decoration: underline;}
.post_article p {margin:4% 0;line-height:2.4rem;}
.post_article p a,.post_article p a span{padding:0;color:#3274ff;}a
.post_article h1,.post_article h2,.post_article h3,.post_article h4,#comments{margin:2rem 0;font-weight:bold;position:relative;}
.post_article h1 {font-size:1.8rem;line-height:1.8rem;}
.post_article h2 {font-size:1.6rem;line-height:1.6rem;}
.post_article h3 {font-size:1.4rem;line-height:1.4rem;}
.post_article h4,#comments {font-size:1.2rem;line-height:1.2rem;}
/* 这个地方应该要处理到H7 */
```
